INSERT INTO BUP_TIPO_IVA(CLAVE_TIPO_IVA, DESCRIPCION, PORC_IVA) 
VALUES ('NOR', 'Comision de IVA Normal', 15);

INSERT INTO BUP_TIPO_IVA(CLAVE_TIPO_IVA, DESCRIPCION, PORC_IVA) 
VALUES ('FRT', 'Comision de IVA fronterizo', 10);

COMMIT;
/