/*
 * $Id: SICA_FDS.sql,v 1.12 2008/02/22 18:25:54 ccovian Exp $
 * Autor: LegoSoft.
 * Fecha: 09/27/2005
 *
 * Scripts para la creacion de dependencias funcionales de la
 * Base de Datos del sistema de cambios SICA.
 *
 */

/* ---------------FK1_SC_CANAL_SEGU_FACULTAD------------------- */

ALTER TABLE SICA_ADMIN.SC_CANAL ADD CONSTRAINT FK1_SC_CANAL_SEGU_FACULTAD
  FOREIGN KEY(FACULTAD) REFERENCES BUPIXE.SEGU_FACULTAD(NOMBRE);

/* ---------------FK1_SC_CANAL_BUP_TIPO_IVA------------------- */

ALTER TABLE SICA_ADMIN.SC_CANAL ADD CONSTRAINT FK1_SC_CANAL_BUP_TIPO_IVA
  FOREIGN KEY(CLAVE_TIPO_IVA) REFERENCES BUPIXE.BUP_TIPO_IVA(CLAVE_TIPO_IVA);

/* ---------------Estructura de clase de SC_DEAL_DETALLE------------------- */

ALTER TABLE SICA_ADMIN.SC_DEAL_DETALLE ADD CONSTRAINT FK_SC_DEAL_DETALLE
  FOREIGN KEY(ID_DEAL_POSICION) REFERENCES SICA_ADMIN.SC_DEAL_POSICION(ID_DEAL_POSICION);

ALTER TABLE SICA_ADMIN.SC_DEAL_DETALLE ADD CONSTRAINT FK_SC_DEAL_DETALLE_ID_DEAL
  FOREIGN KEY(ID_DEAL) REFERENCES SICA_ADMIN.SC_DEAL(ID_DEAL);

ALTER TABLE SICA_ADMIN.SC_DEAL_DETALLE ADD CONSTRAINT FK_SC_DEAL_DET_ID_PLANTILLA
  FOREIGN KEY(ID_PLANTILLA) REFERENCES SICA_ADMIN.SC_PLANTILLA(ID_PLANTILLA);

/* ---------------FK_SC_DEAL_DET_STATUS_LOG_ID------------------- */

ALTER TABLE SICA_ADMIN.SC_DEAL_DETALLE_STATUS_LOG ADD CONSTRAINT FK_SC_DEAL_DET_STATUS_LOG_ID
  FOREIGN KEY(ID_DEAL_POSICION) REFERENCES SICA_ADMIN.SC_DEAL_DETALLE(ID_DEAL_POSICION);

/* ---------------FK_SC_DEAL_LOG_ID_DEAL------------------- */

ALTER TABLE SICA_ADMIN.SC_DEAL_LOG ADD CONSTRAINT FK_SC_DEAL_LOG_ID_DEAL
  FOREIGN KEY(ID_DEAL) REFERENCES SC_DEAL(ID_DEAL);

/* ---------------FK_SC_DEAL_STATUS_LOG_ID_DEAL------------------- */
ALTER TABLE SICA_ADMIN.SC_DEAL_STATUS_LOG ADD CONSTRAINT FK_SC_DEAL_STATUS_LOG_ID_DEAL
  FOREIGN KEY(ID_DEAL) REFERENCES SICA_ADMIN.SC_DEAL(ID_DEAL);

/* ---------------FK_SC_DEAL_STATUS_LOG_ID_DEAL------------------- */
ALTER TABLE SICA_ADMIN.SC_DEAL_STATUS_LOG ADD CONSTRAINT FK_SC_DEAL_STATUS_LOG_ID_DEAL
  FOREIGN KEY(ID_DEAL) REFERENCES SICA_ADMIN.SC_DEAL(ID_DEAL);

/* ---------------FK_SC_LINEA_CREDITO_LOG------------------- */

ALTER TABLE SICA_ADMIN.SC_LINEA_CREDITO_LOG ADD CONSTRAINT FK_SC_LINEA_CREDITO_LOG
  FOREIGN KEY(ID_LINEA_CREDITO) REFERENCES SICA_ADMIN.SC_LINEA_CREDITO(ID_LINEA_CREDITO);

/* ---------------FK_SC_LINEA_OPERACION------------------- */

ALTER TABLE SICA_ADMIN.SC_LINEA_OPERACION ADD CONSTRAINT FK_SC_LINEA_OPERACION
  FOREIGN KEY(ID_BROKER) REFERENCES SICA_ADMIN.SC_BROKER(ID_PERSONA);

/* ---------------FK_SC_LINEA_OPERACION_LOG------------------- */

ALTER TABLE SICA_ADMIN.SC_LINEA_OPERACION_LOG ADD CONSTRAINT FK_SC_LINEA_OPERACION_LOG
  FOREIGN KEY(ID_LINEA_OPERACION) REFERENCES SICA_ADMIN.SC_LINEA_OPERACION(ID_LINEA_OPERACION);

/* ---------------Estructura de la Clase SC_MOVIMIENTO_CONT_DETALLE------------------- */

ALTER TABLE SICA_ADMIN.SC_MOVIMIENTO_CONT_DETALLE ADD CONSTRAINT FK_SC_MOV_CONT_DET_SC_MOV_CONT
  FOREIGN KEY(ID_MOVIMIENTO_CONTABLE) REFERENCES SICA_ADMIN.SC_MOVIMIENTO_CONTABLE(ID_MOVIMIENTO_CONTABLE);

ALTER TABLE SICA_ADMIN.SC_MOVIMIENTO_CONT_DETALLE ADD CONSTRAINT FK_SC_MOV_CONT_DET_SC_DIV
  FOREIGN KEY(ID_DIVISA) REFERENCES SICA_ADMIN.SC_DIVISA(ID_DIVISA);

/* ---------------FK_SC_MOV_CONT_SC_DIV------------------- */

ALTER TABLE SICA_ADMIN.SC_MOVIMIENTO_CONTABLE ADD CONSTRAINT FK_SC_MOV_CONT_SC_DIV
  FOREIGN KEY(ID_DIVISA) REFERENCES SICA_ADMIN.SC_DIVISA(ID_DIVISA);

/* ---------------FK_SC_PLANTILLA_CUENTA_IXE------------------- */
ALTER TABLE SICA_ADMIN.SC_PLANTILLA_CUENTA_IXE ADD CONSTRAINT FK_SC_PLANTILLA_CUENTA_IXE
  FOREIGN KEY(ID_PLANTILLA) REFERENCES SICA_ADMIN.SC_PLANTILLA(ID_PLANTILLA);

/* ---------------FK_SC_PLANTILLA_INTL------------------- */
ALTER TABLE SICA_ADMIN.SC_PLANTILLA_INTL ADD CONSTRAINT FK_SC_PLANTILLA_INTL
  FOREIGN KEY(ID_PLANTILLA) REFERENCES SICA_ADMIN.SC_PLANTILLA(ID_PLANTILLA);

/* ---------------FK_SC_PLANTILLA_NACIONAL------------------- */
ALTER TABLE SICA_ADMIN.SC_PLANTILLA_NACIONAL ADD CONSTRAINT FK_SC_PLANTILLA_NACIONAL
  FOREIGN KEY(ID_PLANTILLA) REFERENCES SICA_ADMIN.SC_PLANTILLA(ID_PLANTILLA);

/* ---------------FK_SC_PLANTILLA_TRAN_NACIONAL------------------- */
ALTER TABLE SICA_ADMIN.SC_PLANTILLA_TRAN_NACIONAL ADD CONSTRAINT FK_SC_PLANTILLA_TRAN_NACIONAL
  FOREIGN KEY(ID_PLANTILLA) REFERENCES SICA_ADMIN.SC_PLANTILLA(ID_PLANTILLA);

/* ---------------FK_SC_POLIZA_SC_DIVISA------------------- */

ALTER TABLE SICA_ADMIN.SC_POLIZA ADD CONSTRAINT FK_SC_POLIZA_SC_DIVISA
  FOREIGN KEY(ID_DIVISA) REFERENCES SICA_ADMIN.SC_DIVISA(ID_DIVISA);

/* ---------------FK_SC_POSICION_DETALLE_ID_POS------------------- */

ALTER TABLE SICA_ADMIN.SC_POSICION_DETALLE ADD CONSTRAINT FK_SC_POSICION_DETALLE_ID_POS
  FOREIGN KEY(ID_POSICION) REFERENCES SICA_ADMIN.SC_POSICION(ID_POSICION);

/* ---------------Estructura de la Clase SC_REVERSO------------------- */

ALTER TABLE SICA_ADMIN.SC_REVERSO ADD CONSTRAINT FK1_SC_REVERSO_SC_DEAL
  FOREIGN KEY(ID_DEAL_ORIGINAL) REFERENCES SC_DEAL(ID_DEAL);

ALTER TABLE SICA_ADMIN.SC_REVERSO ADD CONSTRAINT FK2_SC_REVERSO_SC_DEAL
  FOREIGN KEY(ID_DEAL_BALANCEO) REFERENCES SC_DEAL(ID_DEAL);

ALTER TABLE SICA_ADMIN.SC_REVERSO ADD CONSTRAINT FK3_SC_REVERSO_SC_DEAL
  FOREIGN KEY(ID_DEAL_CORRECCION) REFERENCES SC_DEAL(ID_DEAL);

/* ---------------FK_SC_SWAP_ID_DIVISA------------------- */

ALTER TABLE SICA_ADMIN.SC_SWAP ADD CONSTRAINT FK_SC_SWAP_ID_DIVISA
  FOREIGN KEY(ID_DIVISA) REFERENCES SICA_ADMIN.SC_DIVISA(ID_DIVISA);

/* ---------------Estructura de la Clase SC_TRASPASO_MESA------------------- */

ALTER TABLE SICA_ADMIN.SC_TRASPASO_MESA ADD CONSTRAINT FK1_SC_TRASPASO_MESA_CAMBIO
  FOREIGN KEY(DE_MESA_CAMBIO) REFERENCES SICA_ADMIN.SC_MESA_CAMBIO(ID_MESA_CAMBIO);

ALTER TABLE SICA_ADMIN.SC_TRASPASO_MESA ADD CONSTRAINT FK2_SC_TRASPASO_MESA_CAMBIO
  FOREIGN KEY(A_MESA_CAMBIO) REFERENCES SICA_ADMIN.SC_MESA_CAMBIO(ID_MESA_CAMBIO);

ALTER TABLE SICA_ADMIN.SC_TRASPASO_MESA ADD CONSTRAINT FKC03_SC_TRASPASO_MESA
  FOREIGN KEY(DE_ID_DEAL_POSICION) REFERENCES SICA_ADMIN.SC_DEAL_POSICION(ID_DEAL_POSICION);

ALTER TABLE SICA_ADMIN.SC_TRASPASO_MESA ADD CONSTRAINT FKC04_SC_TRASPASO_MESA
  FOREIGN KEY(A_ID_DEAL_POSICION) REFERENCES SICA_ADMIN.SC_DEAL_POSICION(ID_DEAL_POSICION);

/* ---------------Estructura de clase de SC_TRASPASO_PRODUCTO------------------- */

ALTER TABLE SICA_ADMIN.SC_TRASPASO_PRODUCTO ADD CONSTRAINT FK_SC_TRASPASO_PRODUCTO
  FOREIGN KEY(ID_DEAL_POSICION) REFERENCES SICA_ADMIN.SC_DEAL_POSICION(ID_DEAL_POSICION);

ALTER TABLE SICA_ADMIN.SC_TRASPASO_PRODUCTO ADD CONSTRAINT FK_SC_TRASPASO_PRODUCTO_MN
  FOREIGN KEY(MNEMONICO_TRASPASO) REFERENCES SICA_ADMIN.SC_TIPO_TRASPASO_PRODUCTO(MNEMONICO_TRASPASO);
