/*
 * $Id: CreateIndexes.sql,v 1.14 2008/02/22 18:25:53 ccovian Exp $
 * Autor: LegoSoft.
 * Fecha: 09/29/2005
 *
 * Scripts para la creacion de los indices adicionales a los
 * creados como llaves primarias para la optimizacion de las
 * consultas que realiza el SICA.
 *
 */

/*
 * Lectura de SC_ACTIVIDAD por NOMBRE_ACTIVIDAD, ID_DEAL, ID_DEAL_POSICION, PROCESO, STATUS.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_ACTIVIDAD;

CREATE INDEX SICA_ADMIN.INDX_SC_ACTIVIDAD
  ON SC_ACTIVIDAD(NOMBRE_ACTIVIDAD, ID_DEAL, ID_DEAL_POSICION, PROCESO, STATUS);


/*
 * Lectura del SC_FACTOR_DIVISA de una divisa a otra divisa.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_FACTOR_DIVISA;

CREATE INDEX SICA_ADMIN.INDX_SC_FACTOR_DIVISA
  ON SC_FACTOR_DIVISA(FROM_ID_DIVISA, TO_ID_DIVISA);


/*
 * Lecturas del SC_PLANTILLA por NO_CUENTA
 **/
DROP INDEX SICA_ADMIN.INDX_SC_PLANTILLA;

CREATE  INDEX SICA_ADMIN.INDX_SC_PLANTILLA
   ON SC_PLANTILLA(NO_CUENTA);


/*
 * Lecturas del SC_PLANTILLA_INTL de las divisas que opera
 **/
DROP INDEX SICA_ADMIN.INDX_SC_PLANTILLA_INTL;

CREATE INDEX SICA_ADMIN.INDX_SC_PLANTILLA_INTL
   ON SC_PLANTILLA_INTL(ID_DIVISA);

/*
 * Lecturas del SC_POSICION_LOG por el Blotter en la pantalla
 * de Posicion
 **/
DROP INDEX SICA_ADMIN.INDX_SC_POSICION_LOG;

CREATE INDEX SICA_ADMIN.INDX_SC_POSICION_LOG
   ON SC_POSICION_LOG(ID_MESA_CAMBIO, ID_DIVISA);

/*
 * Lecturas del SC_POSICION a partir de su llave unica
 **/
DROP INDEX SICA_ADMIN.INDX_SC_POSICION;

CREATE UNIQUE INDEX SICA_ADMIN.INDX_SC_POSICION
   ON SC_POSICION(ID_MESA_CAMBIO, ID_DIVISA);

/*
 * Lecturas del SC_POSICION_DETALLE a partir de su encabezado
 * SC_POSICION
 **/
DROP INDEX SICA_ADMIN.INDX_SC_POSICION_DETALLLE;

CREATE INDEX SICA_ADMIN.INDX_SC_POSICION_DETALLE
   ON SC_POSICION_DETALLE(ID_MESA_CAMBIO, ID_DIVISA);

/*
 * Lecturas del SC_DEAL por contrato del SICA
 * de Posicion
 **/
DROP INDEX SICA_ADMIN.INDX_SC_DEAL_NO_CUENTA;

CREATE INDEX SICA_ADMIN.INDX_SC_DEAL_NO_CUENTA
   ON SC_DEAL(NO_CUENTA);

/*
 * Lecturas del SC_DEAL por status en el que
 * se encuentra en el deal.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_DEAL_STAUS;

CREATE INDEX SICA_ADMIN.INDX_SC_DEAL_STATUS
   ON SC_DEAL(STATUS_DEAL, EVENTOS_DEAL);

/*
 * Lecturas del SC_DEAL_LOG obviamente
 * desde el header del deal que tuvo las
 * modificacions.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_DEAL_LOG;

CREATE INDEX SICA_ADMIN.INDX_SC_DEAL_LOG
   ON SC_DEAL_LOG(ID_DEAL);

/*
 * Lecturas del SC_DEAL_LOG obviamente
 * desde el header del deal que tuvo las
 * modificacions en sus detalles.
 * Este campo puede tener muchos valores
 * en NULL.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_DEAL_LOG_DETALLE;

CREATE INDEX SICA_ADMIN.INDX_SC_DEAL_LOG_DETALLE
   ON SC_DEAL_LOG(ID_DEAL_POSICION);

/*
 * Lecturas del SC_DEAL_STATUS_LOG obviamente
 * desde el header del deal que tuvo las
 * modificacions en sus estados.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_DEAL_STATUS_LOG;

CREATE INDEX SICA_ADMIN.INDX_SC_DEAL_STATUS_LOG
   ON SC_DEAL_STATUS_LOG(ID_DEAL);

/*
 * Lecturas del SC_DEAL_DETALLE obviamente
 * desde el header del deal con sus movimientos.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_DEAL_DETALLE;

CREATE INDEX SICA_ADMIN.INDX_SC_DEAL_DETALLE
   ON SC_DEAL_DETALLE(ID_DEAL);

/*
 * Lecturas del SC_DEAL_DETALLE de acuerdo a
 * lo eventos que tiene.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_DEAL_DETALLE_EVENTOS;

CREATE INDEX SICA_ADMIN.INDX_SC_DEAL_DETALLE_ENEVTOS
   ON SC_DEAL_DETALLE(EVENTOS_DETALLE_DEAL);

/*
 * Lecturas del SC_DEAL_DETALLE_STATUS_LOG obviamente
 * desde el detalle del deal con sus movimientos que
 *se tuvo en los estados del deatelle del deal.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_D_DETALLE_STATUS_LOG;

CREATE INDEX SICA_ADMIN.INDX_SC_D_DETALLE_STATUS_LOG
   ON SC_DEAL_DETALLE_STATUS_LOG(ID_DEAL_POSICION);

/*
 * Lecturas del SC_LINEA_CREDITO desde su corporativo.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_LINEA_CREDITO_CORP;

CREATE INDEX SICA_ADMIN.INDX_SC_LINEA_CREDITO_CORP
   ON SC_LINEA_CREDITO(ID_CORPORATIVO);

/*
 * Lecturas del SC_LINEA_CREDITO desde su status.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_LINEA_CREDITO_STATUS;

CREATE INDEX SICA_ADMIN.INDX_SC_LINEA_CREDITO_STATUS
   ON SC_LINEA_CREDITO(STATUS_LINEA);

/*
 * Lecturas del SC_LINEA_CREDITO_LOG, obviamente
 * desde la linea de credito y sus modificaciones
 **/
DROP INDEX SICA_ADMIN.INDX_SC_LINEA_CREDITO_LOG;

CREATE INDEX SICA_ADMIN.INDX_SC_LINEA_CREDITO_LOG
   ON SC_LINEA_CREDITO_LOG(ID_LINEA_CREDITO);

/*
 * Lecturas del SC_LINEA_OPERACION desde su IF.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_LINEA_OPERACION_BROKER;

CREATE INDEX SICA_ADMIN.INDX_SC_LINEA_OPERACION_BROKER
   ON SC_LINEA_OPERACION(ID_BROKER);

/*
 * Lecturas del SC_LINEA_OPERACION desde su status.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_LINEA_OPERACION_STATUS;

CREATE INDEX SICA_ADMIN.INDX_SC_LINEA_OPERACION_STATUS
   ON SC_LINEA_OPERACION(STATUS_LINEA);

/*
 * Lecturas del SC_LINEA_OPERACION_LOG, obviamente
 * desde la linea de operacion y sus modificaciones
 **/
DROP INDEX SICA_ADMIN.INDX_SC_LINEA_OPERACION_LOG;

CREATE INDEX SICA_ADMIN.INDX_SC_LINEA_OPERACION_LOG
   ON SC_LINEA_OPERACION_LOG(ID_LINEA_OPERACION);

/*
 * Lecturas del SC_H_TIPO_CAMBIO, se realiza la
 * lectura de los tipos de cambio de un dia
 **/
DROP INDEX SICA_ADMIN.INDX_SC_H_TIPO_CAMBIO;

CREATE INDEX SICA_ADMIN.INDX_SC_H_TIPO_CAMBIO
   ON SC_H_TIPO_CAMBIO(FECHA);

/*
 * Lecturas del SC_LIMITE, como su llave
 * alterna unica
 **/
DROP INDEX SICA_ADMIN.INDX_SC_LIMITE;

CREATE UNIQUE INDEX SICA_ADMIN.INDX_SC_LIMITE
   ON SC_LIMITE(ID_TIPO_LIMITE, ID_MESA_CAMBIO, ID_DIVISA);

/*
 * Lo utiliza TAS para su Logica de 
 * Reporte de Operaciones a Banxico.
 **/
DROP INDEX derivades1.XPKsc_bitacora_enviadas;
 
CREATE UNIQUE INDEX XPKsc_bitacora_enviadas 
	ON derivades1.SC_BITACORA_ENVIADAS(ID_CONF asc, DIVISA asc);

/*
 * Lecturas del SC_RENGLON_PIZARRON, como su llave alterna unica
 **/
DROP INDEX SICA_ADMIN.INDX_SC_RENGLON_PIZARRON;

CREATE INDEX SICA_ADMIN.INDX_SC_RENGLON_PIZARRON
   ON SC_RENGLON_PIZARRON(ID_CANAL);
   
/*
 * Lecturas de SC_GUIA_CONTABLE_LIQ para la generación de las Liquidaciones Contables.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_GUIA_CONTABLE_LIQ;

CREATE INDEX SICA_ADMIN.INDX_SC_GUIA_CONTABLE_LIQ 
   ON SC_GUIA_CONTABLE_LIQ(MNEMONICO);

DROP INDEX SICA_ADMIN.INDX2_SC_GUIA_CONTABLE_LIQ;

CREATE INDEX SICA_ADMIN.INDX2_SC_GUIA_CONTABLE_LIQ 
   ON SC_GUIA_CONTABLE_LIQ(MNEMONICO, MONEDA);
   
DROP INDEX SICA_ADMIN.INDX3_SC_GUIA_CONTABLE_LIQ;

CREATE INDEX SICA_ADMIN.INDX3_SC_GUIA_CONTABLE_LIQ 
   ON SC_GUIA_CONTABLE_LIQ(MNEMONICO, LIQUIDACION_ESPECIAL);

/*
 * Lecturas de SC_GUIA_CONTABLE_ASIENTO para la generación de los Asientos Contables.
 **/
DROP INDEX SICA_ADMIN.INDX_SC_GUIA_CONTABLE_ASIENTO;

CREATE INDEX SICA_ADMIN.INDX_SC_GUIA_CONTABLE_ASIENTO 
   ON SC_GUIA_CONTABLE_ASIENTO(TIPO_OPERACION, FASE_CONTABLE, MONEDA);

DROP INDEX SICA_ADMIN.INDX2_SC_GUIA_CONTABLE_ASIENTO;

CREATE INDEX SICA_ADMIN.INDX2_SC_GUIA_CONTABLE_ASIENTO 
   ON SC_GUIA_CONTABLE_ASIENTO(TIPO_OPERACION, FASE_CONTABLE);

