/*
 * $Id: SC_ACTIVIDAD.sql,v 1.14 2008/02/22 18:25:11 ccovian Exp $
 * Autor: Jean C. Favila
 * Fecha: 01/17/2006
 *
 * Operaciones de autorizacion.
 */

DROP TABLE SICA_ADMIN.SC_ACTIVIDAD;

CREATE TABLE SICA_ADMIN.SC_ACTIVIDAD (
        ID_ACTIVIDAD NUMBER NOT NULL PRIMARY KEY,
        NOMBRE_ACTIVIDAD VARCHAR2(20) NOT NULL,
        FECHA_CREACION DATE NOT NULL,
        FECHA_TERMINACION DATE NULL,
        ID_DEAL NUMBER NOT NULL,
        ID_DEAL_POSICION NUMBER NULL,
        ID_USUARIO NUMBER NULL,
        RESULTADO VARCHAR2(30) NULL,
        STATUS VARCHAR2(12) NOT NULL,
        PROCESO VARCHAR2(10) NOT NULL,
        VERSION NUMBER DEFAULT 0 NULL
)
;

CREATE PUBLIC SYNONYM SC_ACTIVIDAD FOR SICA_ADMIN.SC_ACTIVIDAD;
/