/*
 * $Id: SC_AUT_MEDIO_CONTACTO.sql,v 1.2 2009/08/03 21:57:04 ccovian Exp $
 * Autor: Jean C. Favila
 * Fecha: 01/23/2009
 *
 * Operaciones de autorizacion.
 */

DROP TABLE SICA_ADMIN.SC_AUT_MEDIO_CONTACTO;

CREATE TABLE SICA_ADMIN.SC_AUT_MEDIO_CONTACTO (
        ID_AUT_MEDIO_CONTACTO NUMBER NOT NULL PRIMARY KEY,
        EMAIL VARCHAR2(80) NOT NULL,
        FECHA_CREACION DATE NOT NULL,
        FECHA_TERMINACION DATE NULL,
        ID_PERSONA NUMBER NOT NULL,
        ID_PROMOTOR NUMBER NOT NULL,
        ID_USUARIO NUMBER NULL,
        STATUS VARCHAR2(12) NOT NULL
)
;

CREATE PUBLIC SYNONYM SC_AUT_MEDIO_CONTACTO FOR SICA_ADMIN.SC_AUT_MEDIO_CONTACTO;
