/*
 * $Id: SC_BITACORA_ENVIADAS.sql,v 1.11 2008/02/22 18:25:12 ccovian Exp $
 * Autor: Javier Cordova (jcordova)
 * Fecha: 31/08/2005
 */

DROP TABLE derivades1.sc_bitacora_enviadas;

CREATE TABLE derivades1.SC_BITACORA_ENVIADAS 
(
    ID_CONF				VARCHAR2(20)	NOT NULL,
    DIVISA          	VARCHAR2(3)   	NOT NULL,
    FOLIO           	NUMBER			NULL,
    CLAVE_CONTRAPARTE	VARCHAR2(30)	NULL,
    NOMBRE          	VARCHAR2(30)	NULL,
    RFC     			VARCHAR2(18)	NULL,
    TIPO_CONTRAPARTE	VARCHAR2(8)		NULL,
    ACCION          	NUMBER			NULL,
    PLAZO           	NUMBER			NULL,
    TIPOOPER        	NUMBER			NULL,
    MONTO           	NUMBER			NULL,
    TIPO            	NUMBER			NULL,
    FECHA_CONCERTACION	DATE			NULL,
    FECHA_LIQUIDACION	DATE			NULL,
    SWAP    			CHAR(1)			NULL,
    ERROR				NUMBER			NULL,
    FECHA_ENVIO			DATE			NULL,
    FOLIO_BANXICO		NUMBER			NULL,
    CREATE_DT 			DATE			NULL,
    ESTATUS          	CHAR(12)		NULL,
    STATUS_ESTRATEGIA	CHAR(2)			NULL,
    NO_CUENTA           VARCHAR2(33)    NULL,
    PROGRESS_RECID      NUMBER			NULL
);

ALTER TABLE derivades1.SC_BITACORA_ENVIADAS ADD (PRIMARY KEY(ID_CONF, DIVISA));

CREATE PUBLIC SYNONYM SC_BITACORA_ENVIADAS FOR derivades1.SC_BITACORA_ENVIADAS;
/