/*
 * $Id: SC_DEAL.sql,v 1.20.34.1 2012/12/18 22:29:16 jarechig Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 03/10/2005
 *
 * Encabezados de los deals.
 */

/* Cuando se modifique la estructura de esta tabla se debera
   de considerar la modificacion de su tabla de su historico
   correspondiente que se llama SC_H_DEAL
 */
 
DROP TABLE SICA_ADMIN.SC_DEAL;

CREATE TABLE SICA_ADMIN.SC_DEAL (
        ID_DEAL NUMBER NOT NULL PRIMARY KEY,
        COMPRA CHAR(1) NOT NULL,
        ENVIAR_AL_CLIENTE CHAR(1) NOT NULL,
        EVENTOS_DEAL CHAR(16) NOT NULL,
        FACTURA CHAR(1) NOT NULL,
        FECHA_CAPTURA DATE NOT NULL,
        FECHA_LIQUIDACION DATE NOT NULL,
        ID_BROKER NUMBER NULL,
        ID_CANAL CHAR(3) NOT NULL,
        ID_DIRECCION_MENSAJERIA NUMBER NULL,
        ID_LIQUIDACION NUMBER NULL,
        ID_PROMOTOR NUMBER NULL,
        ID_USUARIO NUMBER NOT NULL,
        ID_MESA_CAMBIO NUMBER NOT NULL,
        MENSAJERIA CHAR(1) NOT NULL,
        NO_CUENTA VARCHAR2(33) NULL,
        OBSERVACIONES VARCHAR2(512) NULL,
        PAGO_ANTICIPADO CHAR(1) NOT NULL,
        TOMA_EN_FIRME CHAR(1) NOT NULL,
        SIMPLE CHAR(1) NOT NULL,
        STATUS_DEAL CHAR(2) NOT NULL,
        TIPO_VALOR CHAR(4) NOT NULL,
        NOMBRE_FACTURA VARCHAR2(120) NULL,
        RFC_FACTURA VARCHAR2(15) NULL,
        ID_DIR_FACTURA NUMBER NULL,
        ID_FOLIO_SWAP NUMBER NULL,
        FECHA_LIM_CAPT_CONT DATE DEFAULT SYSDATE NULL,
        VERSION NUMBER NULL,
        ACUDIR_CON VARCHAR2(255) NULL,
        LIQUIDACION_ESPECIAL CHAR(5) NULL,
        REVERSO_DE NUMBER NULL,
        REVERSA_A NUMBER NULL,
        LIQUIDACION_ANTICIPADA CHAR(1) DEFAULT '0' NOT NULL,
        TC_COB_USD_DIV NUMBER(16, 8) NULL,
        TC_COB_MXN_USD NUMBER(16, 8) NULL,
        FACTOR_RIESGO NUMBER(12, 6) NULL,
        MONTO_EQUIV_LC NUMBER(16, 2) NULL,
        CAMBIO_RFC CHAR(1) NOT NULL DEFAULT ' ',
        CAMBIO_EMAIL CHAR(1) NOT NULL DEFAULT ' ',
        ID_DIR_FACT_MENS NUMBER NULL,
        EMAIL_FACTURA VARCHAR2(256) NULL,
        EMAIL_FACTURA_OTRO VARCHAR2(50) NULL,
		METODO_PAGO varchar2(100),
		CUENTA_PAGO varchar2(20);
);

CREATE PUBLIC SYNONYM SC_DEAL FOR SICA_ADMIN.SC_DEAL;
/
