/*
 * $Id: SC_DIVISA.sql,v 1.13 2008/02/22 18:25:11 ccovian Exp $
 * Autor: Jean C. Favila.
 * Fecha: 03/01/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_DIVISA;

CREATE TABLE SICA_ADMIN.SC_DIVISA (
  ID_DIVISA CHAR(3) NOT NULL PRIMARY KEY
, DESCRIPCION VARCHAR2(20) NOT NULL
, ICONO_FNAME VARCHAR2(30) NULL
, ID_MONEDA CHAR(2) NULL
, TIPO CHAR(1) NOT NULL
, ORDEN NUMBER NOT NULL
, DIVIDE CHAR(1) DEFAULT 'N' NOT NULL
, DESCRIPCION_EN VARCHAR2(20) NULL
, GRUPO CHAR(3) NULL
, EQUIVALENCIA_METAL NUMBER(16, 2) NULL
, ID_MONEDA_MINDS NUMBER NULL
);

CREATE PUBLIC SYNONYM SC_DIVISA FOR SICA_ADMIN.SC_DIVISA;
/
