/*
 * $Id: SC_ESTADO.sql,v 1.11 2008/02/22 18:25:13 ccovian Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 08/04/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_ESTADO
;

CREATE TABLE SICA_ADMIN.SC_ESTADO (
  ID_ESTADO NUMBER NOT NULL PRIMARY KEY
, ACTUAL CHAR(1) NOT NULL
, ESTADO VARCHAR2(40) NOT NULL
, HORA_INICIO CHAR(5) NULL
, HORA_FIN CHAR(5) NULL
, NOMBRE_APLICACION VARCHAR2(40) NULL
, SIG_ESTADO NUMBER NULL
, URL_APLICACION VARCHAR2(60) NULL
);

CREATE public SYNONYM SC_ESTADO FOR SICA_ADMIN.SC_ESTADO;
/
