/*
 * $Id: SC_FACTOR_DIVISA.sql,v 1.12 2008/02/22 18:25:12 ccovian Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 03/10/2005
 *
 */

/* Cuando se modifique la estructura de esta tabla se debera
   de considerar la modificacion de su tabla de su historico
   correspondiente que se llama SC_H_FACTOR_DIVISA
 */

DROP TABLE SICA_ADMIN.SC_FACTOR_DIVISA;

CREATE TABLE SICA_ADMIN.SC_FACTOR_DIVISA (
  ID_FACTOR_DIVISA NUMBER NOT NULL PRIMARY KEY
, FROM_ID_DIVISA CHAR(3) NOT NULL
, TO_ID_DIVISA CHAR(3) NOT NULL
, FACTOR NUMBER(12, 6) NOT NULL
, FACTOR_COMPRA NUMBER(12, 6) NULL
, METODO_ACTUALIZACION CHAR(1) NOT NULL
, SPREAD_REFERENCIA NUMBER(12, 6) NOT NULL
, SPREAD_COMPRA NUMBER(12, 6) NOT NULL
, SLACK NUMBER(12, 6) NULL
, CARRY NUMBER(12, 6) NOT NULL
, ULTIMA_MODIFICACION DATE NOT NULL
);

CREATE PUBLIC SYNONYM SC_FACTOR_DIVISA FOR SICA_ADMIN.SC_FACTOR_DIVISA;
/
