/*
 * $Id: SC_FACTOR_DIVISA_ACTUAL.sql,v 1.11 2008/02/22 18:25:12 ccovian Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 10/02/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_FACTOR_DIVISA_ACTUAL;

CREATE TABLE SICA_ADMIN.SC_FACTOR_DIVISA_ACTUAL (
  FROM_ID_DIVISA CHAR(3) NOT NULL
, TO_ID_DIVISA CHAR(3) NOT NULL
, ID_FACTOR_DIVISA NUMBER NOT NULL
, ULTIMA_MODIFICACION DATE NOT NULL
);

CREATE PUBLIC SYNONYM SC_FACTOR_DIVISA_ACTUAL FOR SICA_ADMIN.SC_FACTOR_DIVISA_ACTUAL;
/
