/*
 * $Id: SC_GUIA_CONTABLE_LIQ.sql,v 1.11 2008/02/22 18:25:12 ccovian Exp $
 * Autor: Javier Cordova
 * Fecha: 25/10/2006
 */
 
DROP TABLE SICA_ADMIN.SC_GUIA_CONTABLE_LIQ;

CREATE TABLE SICA_ADMIN.SC_GUIA_CONTABLE_LIQ (
        ID_GUIA_CONTABLE_LIQ NUMBER NOT NULL PRIMARY KEY,
        MNEMONICO VARCHAR2(15) NOT NULL,
        CARGO_ABONO CHAR(5) NOT NULL,
        CUENTA_CONTABLE CHAR(10) NOT NULL,
        ENTIDAD CHAR(28) NOT NULL,
        MONEDA VARCHAR2(7) NOT NULL,
        CLAVE_TIPO_LIQUIDACION VARCHAR2(7) NOT NULL,
        CLAVE_FORMA_LIQUIDACION VARCHAR2(7) NOT NULL,
        DESCRIPCION VARCHAR2(100) NOT NULL,
        LIQUIDACION_ESPECIAL CHAR(5) NULL
);

CREATE PUBLIC SYNONYM SC_GUIA_CONTABLE_LIQ FOR SICA_ADMIN.SC_GUIA_CONTABLE_LIQ;
/
