/*
 * $Id: SC_GUIA_CONTABLE_ASIENTO.sql,v 1.11 2008/02/22 18:25:13 ccovian Exp $
 * Autor: Javier Cordova
 * Fecha: 25/10/2006
 */
 
DROP TABLE SICA_ADMIN.SC_GUIA_CONTABLE_ASIENTO;

CREATE TABLE SICA_ADMIN.SC_GUIA_CONTABLE_ASIENTO (
  ID_GUIA_CONTABLE_ASIENTO NUMBER NOT NULL PRIMARY KEY
, TIPO_OPERACION VARCHAR2(6) NOT NULL
, FASE_CONTABLE VARCHAR2(8) NOT NULL
, CARGO_ABONO CHAR(5) NOT NULL
, CUENTA_CONTABLE CHAR(10) NOT NULL
, ENTIDAD CHAR(28) NOT NULL
, MONEDA VARCHAR2(7) NULL
, DESCRIPCION VARCHAR2(40) NOT NULL
);

CREATE PUBLIC SYNONYM SC_GUIA_CONTABLE_ASIENTO FOR SICA_ADMIN.SC_GUIA_CONTABLE_ASIENTO;
/
