/*
 * Autor: Edgar Leija
 * Fecha: 01/17/2006
 *
 */

DROP TABLE SICA_ADMIN.SC_H_SWAP;

CREATE TABLE SICA_ADMIN.SC_H_SWAP (
        ID_FOLIO_SWAP NUMBER NOT NULL PRIMARY KEY,
        COMPRA CHAR(1) NOT NULL,
        FECHA_OPERACION DATE NOT NULL,
        FOLIO_SWAP_INICIO NUMBER NULL, 
        ID_DIVISA CHAR(3) NOT NULL,
        MONTO NUMBER(16,2) NOT NULL,
        MONTO_ASIGNADO NUMBER(16,2) NOT NULL,
        NO_CUENTA VARCHAR2(33) NOT NULL,
        STATUS CHAR(2) NOT NULL,
        TIPO_SWAP CHAR(1) NOT NULL
);

CREATE PUBLIC SYNONYM SC_H_SWAP FOR SICA_ADMIN.SC_H_SWAP;
/


