/*
 * $Id: SC_H_VAR.sql,v 1.11 2008/02/22 18:25:12 ccovian Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 26/01/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_H_VAR;

CREATE TABLE SICA_ADMIN.SC_H_VAR (
  ID_H_VAR NUMBER NOT NULL PRIMARY KEY
, HORA CHAR(5) NOT NULL
, VAR NUMBER(12, 6) NOT NULL
);

CREATE PUBLIC SYNONYM SC_H_VAR FOR SICA_ADMIN.SC_H_VAR;
/

