/*
 * $Id: SC_H_SPREAD.sql,v 1.12 2008/02/22 18:25:11 ccovian Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 26/01/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_H_SPREAD;

CREATE TABLE SICA_ADMIN.SC_H_SPREAD (
        ID_SPREAD NUMBER NOT NULL PRIMARY KEY,
        CLAVE_FORMA_LIQUIDACION CHAR(6) NOT NULL,
        ID_MESA_CAMBIO NUMBER NOT NULL,
        ID_CANAL CHAR(3) NOT NULL,
        ID_DIVISA CHAR(3) NOT NULL,
        COMPRA_72HR NUMBER(12,6) NOT NULL,
        VENTA_72HR NUMBER(12,6) NOT NULL,
        COMPRA_SPOT NUMBER(12,6) NOT NULL,
        VENTA_SPOT NUMBER(12,6) NOT NULL,
        COMPRA_TOM NUMBER(12,6) NOT NULL,
        VENTA_TOM NUMBER(12,6) NOT NULL,
        COMPRA_CASH NUMBER(12,6) NOT NULL,
        VENTA_CASH NUMBER(12,6) NOT NULL,
        ULTIMA_MODIFICACION DATE NOT NULL,
        COMPRA_VFUT NUMBER(12,6) DEFAULT 0.0 NOT NULL,
        VENTA_VFUT NUMBER(12,6) DEFAULT 0.0 NOT NULL 
);

CREATE PUBLIC SYNONYM SC_H_SPREAD FOR SICA_ADMIN.SC_H_SPREAD;
/
