/*
 * $Id: SC_H_DEAL_DETALLE_STATUS_LOG.sql,v 1.11 2008/02/22 18:25:13 ccovian Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 03/10/2005
 *
 */
 
DROP TABLE SICA_ADMIN.SC_H_DEAL_DETALLE_STATUS_LOG;

CREATE TABLE SICA_ADMIN.SC_H_DEAL_DETALLE_STATUS_LOG (
  ID_DETALLE_STATUS_LOG NUMBER NOT NULL PRIMARY KEY
, FECHA_CAMBIO DATE NOT NULL
, ID_DEAL_POSICION NUMBER NULL
, STATUS_ANTERIOR CHAR(2) NOT NULL
, STATUS_NUEVO CHAR(2) NOT NULL
);

CREATE PUBLIC SYNONYM SC_H_DEAL_DETALLE_STATUS_LOG FOR SICA_ADMIN.SC_H_DEAL_DETALLE_STATUS_LOG;
/

