/*
 * $Id: SC_LINEA_OPERACION_LOG.sql,v 1.12 2008/02/22 18:25:11 ccovian Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 14/02/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_LINEA_OPERACION_LOG;

CREATE TABLE SICA_ADMIN.SC_LINEA_OPERACION_LOG (
        ID_LINEA_OPERACION_LOG NUMBER NOT NULL PRIMARY KEY,
        FACTOR_DIVISA NUMBER(12,6) NULL,
        FECHA_OPERACION DATE NOT NULL,
        ID_DEAL_POSICION NUMBER NULL,
        ID_DIVISA CHAR(3) NULL,
        ID_LINEA_OPERACION NUMBER NOT NULL,
        ID_USUARIO NUMBER NOT NULL,
        IMPORTE NUMBER(16,2) NOT NULL,
        TIPO_OPER CHAR(2) NOT NULL,
        OBSERVACIONES VARCHAR2(60) NULL 
);

CREATE PUBLIC SYNONYM SC_LINEA_OPERACION_LOG FOR SICA_ADMIN.SC_LINEA_OPERACION_LOG;
/
