/*
 * $Id: SC_LINEA_OPERACION.sql,v 1.11 2008/02/22 18:25:12 ccovian Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 10/02/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_LINEA_OPERACION;

CREATE TABLE SICA_ADMIN.SC_LINEA_OPERACION (
        ID_LINEA_OPERACION NUMBER NOT NULL PRIMARY KEY,
        ID_BROKER NUMBER NOT NULL,
        IMPORTE NUMBER(16,2) NOT NULL,
        NUMERO_EXCEPCIONES NUMBER(3) NOT NULL,
        STATUS_LINEA CHAR(2) NOT NULL,
        ULTIMA_MODIFICACION DATE NOT NULL,
        USO_LINEA NUMBER(16,2) NOT NULL 
);

CREATE PUBLIC SYNONYM SC_LINEA_OPERACION FOR SICA_ADMIN.SC_LINEA_OPERACION;
/
