/*
 * $Id: SC_LINEA_CREDITO.sql,v 1.11 2008/02/22 18:25:13 ccovian Exp $
 * Autor: Ricardo Legorreta H., Javier Cordova (jcordova)
 * Fecha: 10/02/2005
 */

DROP TABLE SICA_ADMIN.SC_LINEA_CREDITO;

CREATE TABLE SICA_ADMIN.SC_LINEA_CREDITO (
        ID_LINEA_CREDITO NUMBER NOT NULL PRIMARY KEY,
        ID_CORPORATIVO NUMBER NOT NULL,
        USA_LINEA_CREDITO NUMBER NOT NULL,
        IMPORTE NUMBER(16,2) NOT NULL,
        USO_LINEA NUMBER(16,2) NOT NULL,
        PROMEDIO_LINEA NUMBER(16,2) NOT NULL,
        ULTIMA_MODIFICACION DATE NOT NULL,
        NUMERO_EXCEPCIONES NUMBER(3) NOT NULL,
        NUMERO_EXCEPCIONES_MES NUMBER(3) NOT NULL,
        VENCIMIENTO DATE NOT NULL,
        STATUS_LINEA CHAR(2) NOT NULL 
);

CREATE PUBLIC SYNONYM SC_LINEA_CREDITO FOR SICA_ADMIN.SC_LINEA_CREDITO;
/
