/*
 * $Id: SC_LINEA_CREDITO_LOG.sql,v 1.12 2008/02/22 18:25:12 ccovian Exp $
 * Autor: Ricardo Legorreta H., Javier Cordova (jcordova)
 * Fecha: 10/02/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_LINEA_CREDITO_LOG;

CREATE TABLE SICA_ADMIN.SC_LINEA_CREDITO_LOG (
        ID_LINEA_CREDITO_LOG NUMBER NOT NULL PRIMARY KEY,
        ID_LINEA_CREDITO NUMBER NOT NULL,
        TIPO_OPER CHAR(2) NOT NULL,
        IMPORTE NUMBER(16,2) NOT NULL,
        FECHA_OPERACION DATE NOT NULL,
        ID_DEAL_DETALLE NUMBER NULL,
        ID_DIVISA CHAR(3) NULL,
        FACTOR_DIVISA NUMBER(12,6) NULL,
        OBSERVACIONES VARCHAR2(60) NULL,
        ID_USUARIO NUMBER NOT NULL
);

CREATE PUBLIC SYNONYM SC_LINEA_CREDITO_LOG FOR SICA_ADMIN.SC_LINEA_CREDITO_LOG;
/
