/*
 * $Id: SC_LINE_CAMBIO_LOG.sql,v 1.3 2008/12/26 23:17:36 ccovian Exp $
 * Autor: Jean C. Favila
 * Fecha: 15/09/2008
 *
 */

DROP TABLE SICA_ADMIN.SC_LINEA_CAMBIO_LOG;

CREATE TABLE SICA_ADMIN.SC_LINEA_CAMBIO_LOG (
        ID_LINEA_CAMBIO_LOG NUMBER NOT NULL PRIMARY KEY,
        ID_LINEA_CAMBIO NUMBER NOT NULL,
        TIPO_OPER CHAR(2) NOT NULL,
        IMPORTE NUMBER(16,2) NOT NULL,
        FECHA_OPERACION DATE NOT NULL,
        ID_DEAL_DETALLE NUMBER NULL,
        ID_DIVISA CHAR(3) NULL,
        FACTOR_DIVISA NUMBER(14,8) NULL,
        OBSERVACIONES VARCHAR2(60) NULL,
        ID_USUARIO NUMBER NOT NULL
);

CREATE PUBLIC SYNONYM SC_LINEA_CAMBIO_LOG FOR SICA_ADMIN.SC_LINEA_CAMBIO_LOG;
/
