/*
 * $Id: SC_LOG_AUDITORIA.sql,v 1.1 2008/06/17 16:13:27 ccovian Exp $
 * Autor: Jean C. Favila
 * Fecha: 26/05/2008
 *
 * Log de auditoria de operaciones SICA.
 */

 DROP TABLE SICA_ADMIN.SC_LOG_AUDITORIA
 ;

 CREATE TABLE SICA_ADMIN.SC_LOG_AUDITORIA (
    ID_LOG_AUDITORIA CHAR(32) NOT NULL PRIMARY KEY,
    DATOS_ADICIONALES VARCHAR2(512) NULL,
    DIRECCION_IP VARCHAR2(20) NOT NULL,
    FECHA DATE NOT NULL,
    ID_DEAL NUMBER NULL,
    ID_PERSONA NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    TICKET CHAR(32) NOT NULL,
    TIPO_OPERACION VARCHAR2(50) NOT NULL
 )
 ;

 CREATE PUBLIC SYNONYM SC_LOG_AUDITORIA FOR SICA_ADMIN.SC_LOG_AUDITORIA;
/

