/*
 * $Id: SC_MOVIMIENTO_CONTABLE.sql,v 1.15 2008/08/11 20:25:09 ccovian Exp $
 * Autor: Edgar Leija, Javier Cordova
 * Fecha: 16/10/2006
 */
 
DROP TABLE SICA_ADMIN.SC_MOVIMIENTO_CONTABLE;

CREATE TABLE SICA_ADMIN.SC_MOVIMIENTO_CONTABLE (
        ID_MOVIMIENTO_CONTABLE CHAR(32) NOT NULL PRIMARY KEY,
        ID_DEAL NUMBER NOT NULL,
        CLIENTE VARCHAR2(120) NULL,
        FECHA_VALOR DATE NOT NULL,
        FASE_CONTABLE VARCHAR2(3) NOT NULL,
        TIPO_FECHA_VALOR CHAR(4) NOT NULL,
        MNEMONICO VARCHAR2(15) NULL,
        TIPO_DEAL VARCHAR2(15) NOT NULL,
        TIPO_OPERACION VARCHAR2(6) NOT NULL,
        ID_USUARIO NUMBER NOT NULL,
        SUCURSAL_ORIGEN VARCHAR2(10) NOT NULL,
        STATUS_ACTUAL VARCHAR2(10) NOT NULL,
        STATUS_ANTERIOR VARCHAR2(10) NOT NULL,
        TIPO_CAMBIO NUMBER(14,8) NOT NULL,
        STATUS_PROCESO CHAR(1) DEFAULT '0' NOT NULL,
        FECHA_CREACION DATE NOT NULL,
        FECHA_PROCESAMIENTO DATE NULL,
        ID_DIVISA CHAR(3) NOT NULL,
        FOLIO_DETALLE NUMBER(2) NULL,
        LIQUIDACION_ESPECIAL CHAR(5) NULL,
        ID_DEAL_POSICION NUMBER DEFAULT 0 NOT NULL,
        CLAVE_REFERENCIA VARCHAR2(10) NULL
);

CREATE PUBLIC SYNONYM SC_MOVIMIENTO_CONTABLE FOR SICA_ADMIN.SC_MOVIMIENTO_CONTABLE;
/