/*
 * $Id: SC_MOVIMIENTO_CONT_DETALLE.sql,v 1.13 2008/02/22 18:25:13 ccovian Exp $
 * Autor: Edgar Leija, Javier Cordova
 * Fecha: 16/10/2006
 */
 
DROP TABLE SICA_ADMIN.SC_MOVIMIENTO_CONT_DETALLE;

CREATE TABLE SICA_ADMIN.SC_MOVIMIENTO_CONT_DETALLE (
  ID_MOVIMIENTO_CONT_DETALLE CHAR(32) NOT NULL PRIMARY KEY
, ID_MOVIMIENTO_CONTABLE CHAR(32) NOT NULL 
, TIPO_DETALLE VARCHAR2(30) NOT NULL
, MONTO NUMBER(16, 2) NOT NULL
, ID_DIVISA CHAR(3) NOT NULL
);

CREATE PUBLIC SYNONYM SC_MOVIMIENTO_CONT_DETALLE FOR SICA_ADMIN.SC_MOVIMIENTO_CONT_DETALLE;
/