/*
 * $Id: SC_MESA_CAMBIO.sql,v 1.11 2008/02/22 18:25:12 ccovian Exp $
 * Autor: Jean C. Favila.
 * Fecha: 06/01/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_MESA_CAMBIO
;

CREATE TABLE SICA_ADMIN.SC_MESA_CAMBIO (
  ID_MESA_CAMBIO NUMBER NOT NULL PRIMARY KEY
, NOMBRE CHAR(10) NOT NULL
, ID_DIVISA_REFERENCIA CHAR(3) NOT NULL
, REPORTA_BANXICO CHAR(1) DEFAULT 'S' NOT NULL
);

CREATE PUBLIC SYNONYM SC_MESA_CAMBIO FOR SICA_ADMIN.SC_MESA_CAMBIO;
/