/*
 * $Id: SC_MAXIMO_DEAL.sql,v 1.11 2008/02/22 18:25:13 ccovian Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 14/02/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_MAXIMO_DEAL
;

CREATE TABLE SICA_ADMIN.SC_MAXIMO_DEAL (
  ID_DIVISA CHAR(3) NOT NULL
, ID_MESA_CAMBIO NUMBER NOT NULL
, MONTO_MAXIMO NUMBER(16, 2) NOT NULL
, PRIMARY KEY (ID_DIVISA, ID_MESA_CAMBIO)
);

CREATE PUBLIC SYNONYM SC_MAXIMO_DEAL FOR SICA_ADMIN.SC_MAXIMO_DEAL;
/
