/*
 * $Id: SC_PARAMETRO.sql,v 1.11 2008/02/22 18:25:12 ccovian Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 04/02/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_PARAMETRO;

CREATE TABLE SICA_ADMIN.SC_PARAMETRO (
  ID_PARAMETRO VARCHAR2(40) NOT NULL PRIMARY KEY
, CADUCIDAD DATE NULL
, TIPO_VALOR CHAR(1) NULL
, VALOR VARCHAR2(125) NULL
);

CREATE PUBLIC SYNONYM SC_PARAMETRO FOR SICA_ADMIN.SC_PARAMETRO;
/
