/*
* $Id: SC_POSICION_DETALLE.sql,v 1.11 2008/02/22 18:25:13 ccovian Exp $
* Autor: Ricardo Legorreta H.
* Fecha: 03/10/2005
*
*/

/* Cuando se modifique la estructura de esta tabla se debera
  de considerar la modificacion de su tabla de su historico
  correspondiente que se llama SC_H_POSICION_DETALLE
*/

DROP TABLE SICA_ADMIN.SC_POSICION_DETALLE;

CREATE TABLE SICA_ADMIN.SC_POSICION_DETALLE (
        ID_POSICION_DETALLE NUMBER NOT NULL PRIMARY KEY
        CLAVE_FORMA_LIQUIDACION CHAR(6) NOT NULL,
        ID_POSICION NUMBER NOT NULL,
        ID_CANAL CHAR(3) NOT NULL,
        ID_DIVISA CHAR(3) NOT NULL,
        ID_MESA_CAMBIO NUMBER NOT NULL,
        COMPRA_CASH NUMBER(18,2) NOT NULL,
        VENTA_CASH NUMBER(18,2) NOT NULL,
        COMPRA_TOM NUMBER(18,2) NOT NULL,
        VENTA_TOM NUMBER(18,2) NOT NULL,
        COMPRA_SPOT NUMBER(18,2) NOT NULL,
        VENTA_SPOT NUMBER(18,2) NOT NULL,
        COMPRA_IN_CASH NUMBER(18,2) NOT NULL,
        VENTA_IN_CASH NUMBER(18,2) NOT NULL,
        COMPRA_IN_TOM NUMBER(18,2) NOT NULL,
        VENTA_IN_TOM NUMBER(18,2) NOT NULL,
        COMPRA_IN_SPOT NUMBER(18,2) NOT NULL,
        VENTA_IN_SPOT NUMBER(18,2) NOT NULL,
        COMPRA_MN_CLIENTE_CASH NUMBER(18,2) NOT NULL,
        VENTA_MN_CLIENTE_CASH NUMBER(18,2) NOT NULL,
        COMPRA_MN_CLIENTE_TOM NUMBER(18,2) NOT NULL,
        VENTA_MN_CLIENTE_TOM NUMBER(18,2) NOT NULL,
        COMPRA_MN_CLIENTE_SPOT NUMBER(18,2) NOT NULL,
        VENTA_MN_CLIENTE_SPOT NUMBER(18,2) NOT NULL,
        COMPRA_MN_PIZARRON_CASH NUMBER(18,2) NOT NULL,
        VENTA_MN_PIZARRON_CASH NUMBER(18,2) NOT NULL,
        COMPRA_MN_PIZARRON_TOM NUMBER(18,2) NOT NULL,
        VENTA_MN_PIZARRON_TOM NUMBER(18,2) NOT NULL,
        COMPRA_MN_PIZARRON_SPOT NUMBER(18,2) NOT NULL,
        VENTA_MN_PIZARRON_SPOT NUMBER(18,2) NOT NULL,
        COMPRA_MN_MESA_CASH NUMBER(18,2) NOT NULL,
        VENTA_MN_MESA_CASH NUMBER(18,2) NOT NULL,
        COMPRA_MN_MESA_TOM NUMBER(18,2) NOT NULL,
        VENTA_MN_MESA_TOM NUMBER(18,2) NOT NULL,
        COMPRA_MN_MESA_SPOT NUMBER(18,2) NOT NULL,
        VENTA_MN_MESA_SPOT NUMBER(18,2) NOT NULL,
        POSICION_INICIAL_CASH NUMBER(18,2) NOT NULL,
        POSICION_INICIAL_TOM NUMBER(18,2) NOT NULL,
        POSICION_INICIAL_SPOT NUMBER(18,2) NOT NULL,
        POSICION_INICIAL_MN_CASH NUMBER(18,2) NOT NULL,
        POSICION_INICIAL_MN_TOM NUMBER(18,2) NOT NULL,
        POSICION_INICIAL_MN_SPOT NUMBER(18,2) NOT NULL,
        POSICION_INICIAL_72HR NUMBER(18,2) NULL,
        POSICION_INICIAL_VFUT NUMBER(18,2) NULL,
        POSICION_INICIAL_MN_72HR NUMBER(18,2) NULL,
        POSICION_INICIAL_MN_VFUT NUMBER(18,2) NULL,
        COMPRA_72HR NUMBER(18,2) NULL,
        VENTA_72HR NUMBER(18,2) NULL,
        COMPRA_VFUT NUMBER(18,2) NULL,
        VENTA_VFUT NUMBER(18,2) NULL,
        COMPRA_IN_72HR NUMBER(18,2) NULL,
        VENTA_IN_72HR NUMBER(18,2) NULL,
        COMPRA_IN_VFUT NUMBER(18,2) NULL,
        VENTA_IN_VFUT NUMBER(18,2) NULL,
        COMPRA_MN_CLIENTE_72HR NUMBER(18,2) NULL,
        VENTA_MN_CLIENTE_72HR NUMBER(18,2) NULL,
        COMPRA_MN_CLIENTE_VFUT NUMBER(18,2) NULL,
        VENTA_MN_CLIENTE_VFUT NUMBER(18,2) NULL,
        COMPRA_MN_PIZARRON_72HR NUMBER(18,2) NULL,
        VENTA_MN_PIZARRON_72HR NUMBER(18,2) NULL,
        COMPRA_MN_PIZARRON_VFUT NUMBER(18,2) NULL,
        VENTA_MN_PIZARRON_VFUT NUMBER(18,2) NULL,
        COMPRA_MN_MESA_72HR NUMBER(18,2) NULL,
        VENTA_MN_MESA_72HR NUMBER(18,2) NULL,
        COMPRA_MN_MESA_VFUT NUMBER(18,2) NULL,
        VENTA_MN_MESA_VFUT NUMBER(18,2) NULL
);

CREATE PUBLIC SYNONYM SC_POSICION_DETALLE FOR SICA_ADMIN.SC_POSICION_DETALLE;
/