/*
 * $Id: SC_PLANTILLA_INTL.sql,v 1.11 2008/02/22 18:25:12 ccovian Exp $
 * Autor: Ricardo Legorreta H
 * Fecha: 10/02/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_PLANTILLA_INTL;

CREATE TABLE SICA_ADMIN.SC_PLANTILLA_INTL (
        ID_PLANTILLA NUMBER NOT NULL PRIMARY KEY,
        CLAVE_BANCO VARCHAR2(30) NULL,
        CLAVE_BANCO_INTERM VARCHAR2(30) NULL,
        CUENTA_BANCO_INTERM VARCHAR2(33) NULL,
        ID_DIVISA CHAR(3) NOT NULL,
        ID_PAIS VARCHAR2(8) NULL,
        NOMBRE_BANCO VARCHAR2(80) NOT NULL,
        NOMBRE_BANCO_INTERM VARCHAR2(80) NULL,
        NO_CUENTA_BENEFICIARIO VARCHAR2(33) NOT NULL,
        TIPO_CUENTA_BANCO CHAR(4) NOT NULL,
        TIPO_CUENTA_BANCO_INTERM CHAR(4) NULL,
        INSTR_BCO_BENEFICIARIO VARCHAR2(144) NULL,
        INSTR_BCO_INTERMEDIARIO VARCHAR2(72) NULL,
        ID_PAIS_INTERM VARCHAR2(8) NULL 
);

CREATE PUBLIC SYNONYM SC_PLANTILLA_INTL FOR SICA_ADMIN.SC_PLANTILLA_INTL;
/