/*
 * $Id: SC_PRECIO_REFERENCIA_ACTUAL.sql,v 1.11 2008/02/22 18:25:13 ccovian Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 10/02/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_PRECIO_REFERENCIA_ACTUAL;

CREATE TABLE SICA_ADMIN.SC_PRECIO_REFERENCIA_ACTUAL (
  ID_PRECIO_REFERENCIA NUMBER NOT NULL PRIMARY KEY
, ULTIMA_MODIFICACION DATE NOT NULL
);

CREATE PUBLIC SYNONYM SC_PRECIO_REFERENCIA_ACTUAL FOR SICA_ADMIN.SC_PRECIO_REFERENCIA_ACTUAL;
/
