/*
 * $Id: SC_PLANTILLA_CUENTA_IXE.sql,v 1.11 2008/02/22 18:25:12 ccovian Exp $
 * Autor: Ricardo Legorreta H., Javier Cordova
 * Fecha: 10/02/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_PLANTILLA_CUENTA_IXE;

CREATE TABLE SICA_ADMIN.SC_PLANTILLA_CUENTA_IXE (
  ID_PLANTILLA NUMBER NOT NULL PRIMARY KEY
, NO_CUENTA_IXE VARCHAR2(33) NOT NULL
);

CREATE PUBLIC SYNONYM SC_PLANTILLA_CUENTA_IXE FOR SICA_ADMIN.SC_PLANTILLA_CUENTA_IXE;
/