/*
 * $Id: SC_POLIZA.sql,v 1.14 2008/08/11 20:25:09 ccovian Exp $
 * Autor: Gustavo Gonzalez, Edgar Leija, Javier Cordova
 * Fecha: 16/10/2006
 */
 
DROP TABLE SICA_ADMIN.SC_POLIZA;

CREATE TABLE SICA_ADMIN.SC_POLIZA (
        ID_POLIZA CHAR(32)NOT NULL PRIMARY KEY,
        FECHA_VALOR DATE NOT NULL,
        CUENTA_CONTABLE CHAR(10) NOT NULL,
        ENTIDAD CHAR(28) NOT NULL,
        CARGO_ABONO CHAR(5) NOT NULL,
        ID_DIVISA CHAR(3) NOT NULL,
        IMPORTE NUMBER(16,2) NOT NULL,
        ID_DEAL NUMBER NOT NULL,
        REFERENCIA VARCHAR2(120) NOT NULL,
        FECHA_CREACION DATE NOT NULL,
        TIPO_DEAL VARCHAR2(15) NOT NULL,
        SUCURSAL_ORIGEN VARCHAR2(10) NOT NULL,
        CLIENTE VARCHAR2(120) NULL,
        FECHA_PROCESAMIENTO DATE NULL,
        STATUS_PROCESO CHAR(1) DEFAULT '0' NOT NULL,
        FOLIO_DETALLE NUMBER(2) NULL,
        TIPO_CAMBIO NUMBER(16,6) DEFAULT 1.0 NOT NULL,
        NO_CONTRATO_SICA VARCHAR2(33) DEFAULT '' NULL,
        CLAVE_REFERENCIA VARCHAR2(10) NULL

};

CREATE PUBLIC SYNONYM SC_POLZA FOR SICA_ADMIN.SC_POLIZA;
/