/*
 * $Id: SC_PLANTILLA_NACIONAL.sql,v 1.11 2008/02/22 18:25:13 ccovian Exp $
 * Autor: Ricardo Legorreta H, Javier Cordova (jcordova).
 * Fecha: 11/02/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_PLANTILLA_NACIONAL;

CREATE TABLE SICA_ADMIN.SC_PLANTILLA_NACIONAL (
  ID_PLANTILLA NUMBER NOT NULL PRIMARY KEY
);

CREATE PUBLIC SYNONYM SC_PLANTILLA_NACIONAL FOR SICA_ADMIN.SC_PLANTILLA_NACIONAL;
/