/*
 * $Id: SC_REVERSO_DETALLE.sql,v 1.1 2008/06/17 16:13:27 ccovian Exp $
 * Autor: Jean C. Favila
 * Fecha: 16/11/2007
 *
 */
DROP TABLE SICA_ADMIN.SC_REVERSO_DETALLE
;

CREATE TABLE SICA_ADMIN.SC_REVERSO_DETALLE (
    ID_REVERSO_DETALLE NUMBER NOT NULL PRIMARY KEY,
    ID_REVERSO NUMBER NOT NULL,
    ID_DEAL_POSICION NUMBER NOT NULL,
    MONTO_NUEVO NUMBER(16, 2) NUMBER NULL,
    TIPO_CAMBIO_NUEVO NUMBER(14, 8) NUMBER NULL
)
;

CREATE PUBLIC SYNONYM SC_REVERSO_DETALLE FOR SICA_ADMIN.SC_REVERSO_DETALLE;
/
