/*
 * $Id: SC_REVERSO.sql,v 1.11 2008/06/17 16:13:27 ccovian Exp $
 * Autor: Javier Cordova.
 * Fecha: 30/04/2007
 *
 * Reversos de deals.
 */

DROP TABLE SICA_ADMIN.SC_REVERSO;

CREATE TABLE SICA_ADMIN.SC_REVERSO (
    ID_REVERSO NUMBER NOT NULL PRIMARY KEY,
    ID_DEAL_ORIGINAL NUMBER NOT NULL,
    ID_DEAL_BALANCEO NUMBER NULL,
    ID_DEAL_CORRECCION NUMBER NULL,
    FECHA DATE NOT NULL,
    FECHA_AUTORIZACION DATE NULL,
    ID_USUARIO NUMBER NOT NULL,
    ID_USUARIO_AUTORIZACION NUMBER NULL,
    OBSERVACIONES VARCHAR2(512) NULL
    POR_CANCELACION CHAR(1) NOT NULL,
    POR_NO_CUENTA VARCHAR2(33) NULL,
    POR_FECHA_VALOR CHAR(4) NULL,
    STATUS_REVERSO CHAR(2) NOT NULL,
    DATOS_ADICIONALES VARCHAR2(512) NULL,
    VERSION NUMBER NOT NULL
);

CREATE PUBLIC SYNONYM SC_REVERSO FOR SICA_ADMIN.SC_REVERSO;
/
