/*
 * $Id: SC_SWAP.sql,v 1.11 2008/02/22 18:25:13 ccovian Exp $
 * Autor: Javier Cordova.
 * Fecha: 01/17/2006
 *
 * Operaciones SWAP.
 */

DROP TABLE SICA_ADMIN.SC_SWAP;

CREATE TABLE SICA_ADMIN.SC_SWAP (
        ID_FOLIO_SWAP NUMBER NOT NULL PRIMARY KEY,
        TIPO_SWAP CHAR(1) NOT NULL,
        NO_CUENTA VARCHAR2(33) NOT NULL,
        COMPRA CHAR(1) NOT NULL,
        MONTO NUMBER(16,2) NOT NULL,
        MONTO_ASIGNADO NUMBER(16,2) NOT NULL,
        FOLIO_SWAP_INICIO NUMBER,
        STATUS CHAR(2) NOT NULL,
        FECHA_OPERACION DATE NOT NULL,
        ID_DIVISA CHAR(3) NOT NULL 
);

CREATE PUBLIC SYNONYM SC_SWAP FOR SICA_ADMIN.SC_SWAP;
/


