/*
 * $Id: SC_TIPO_TRASPASO_PRODUCTO.sql,v 1.11 2008/02/22 18:25:12 ccovian Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 14/02/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_TIPO_TRASPASO_PRODUCTO;

CREATE TABLE SICA_ADMIN.SC_TIPO_TRASPASO_PRODUCTO (
        MNEMONICO_TRASPASO VARCHAR2(15) NOT NULL PRIMARY KEY,
        DESCRIPCION VARCHAR2(40) NOT NULL,
        NETEO CHAR(1) NOT NULL,
        DE CHAR(6) NOT NULL,
        DE_OPER CHAR(2) NOT NULL,
        DE_SIGNO NUMBER NOT NULL,
        A CHAR(6) NOT NULL,
        A_OPER CHAR(2) NOT NULL,
        A_SIGNO NUMBER NOT NULL,
        VAL_MONTO VARCHAR2(10) NULL
);

CREATE PUBLIC SYNONYM SC_TIPO_TRASPASO_PRODUCTO FOR SICA_ADMIN.SC_TIPO_TRASPASO_PRODUCTO;
/