/*
 * $Id: SC_TIPO_LIMITE.sql,v 1.11 2008/02/22 18:25:13 ccovian Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 26/01/2005
 *
 */

DROP TABLE SICA_ADMIN.SC_TIPO_LIMITE;

CREATE TABLE SICA_ADMIN.SC_TIPO_LIMITE (
  ID_TIPO_LIMITE NUMBER NOT NULL PRIMARY KEY
, ID_DIVISA CHAR(3) NULL
, ES_GLOBAL CHAR(1) NOT NULL
, METODO_CALCULO VARCHAR2(40) NOT NULL
, NOMBRE VARCHAR2(40) NOT NULL
, ES_AL_CIERRE CHAR(1) NOT NULL
);

CREATE PUBLIC SYNONYM SC_TIPO_LIMITE FOR SICA_ADMIN.SC_TIPO_LIMITE;
/