/*
 * $Id: SC_TRASPASO_MESA.sql,v 1.11 2008/02/22 18:25:11 ccovian Exp $
 * Autor: Javier Cordova (jcordova).
 * Fecha: 07/02/2006
 */
 
DROP TABLE SICA_ADMIN.SC_TRASPASO_MESA;

CREATE TABLE SICA_ADMIN.SC_TRASPASO_MESA (
        ID_TRASPASO_MESA NUMBER NOT NULL PRIMARY KEY, 
        DE_MESA_CAMBIO NUMBER NOT NULL,
        A_MESA_CAMBIO NUMBER NOT NULL,
        DIVISA VARCHAR2(3) NOT NULL,
        TIPO_CAMBIO NUMBER(16,6) NOT NULL,
        TIPO_CAMBIO_DIVISA_REFERENCIA NUMBER(16,6) NOT NULL,
        DE_ID_DEAL_POSICION NUMBER NOT NULL,
        A_ID_DEAL_POSICION NUMBER NOT NULL,
        FECHA_OPERACION DATE NOT NULL
);

CREATE PUBLIC SYNONYM SC_TRASPASO_MESA FOR SICA_ADMIN.SC_TRASPASO_MESA;
/
