/*
 * $Id: SC_TC_MIN_MAX_TELLER.sql,v 1.3 2009/08/03 21:55:53 ccovian Exp $
 * Autor: Gustavo Gonzalez.
 * Fecha: 03/12/2007
 *
 * Tipos de Cambio Minimos y Maximos para operados por el Teller.
 */
DROP TABLE SICA_ADMIN.SC_TC_MIN_MAX_TELLER;

CREATE TABLE SICA_ADMIN.SC_TC_MIN_MAX_TELLER (
    ID_TC_MIN_MAX NUMBER NOT NULL PRIMARY KEY,
	TIPO_CAMBIO_MINIMO_CPA NUMBER(14, 8) NOT NULL,
	TIPO_CAMBIO_MAXIMO_CPA NUMBER(14, 8) NOT NULL,
	TIPO_CAMBIO_MINIMO_VTA NUMBER(14, 8) NOT NULL,
	TIPO_CAMBIO_MAXIMO_VTA NUMBER(14, 8) NOT NULL,
	ID_CANAL CHAR(3) NOT NULL,	
	CIERRE CHAR(1) NOT NULL,
	FECHA DATE DEFAULT SYSDATE NOT NULL
);

CREATE PUBLIC SYNONYM SC_TC_MIN_MAX_TELLER FOR SICA_ADMIN.SC_TC_MIN_MAX_TELLER;
/