/*
 * $Id: SC_TIPO_PIZARRON.sql,v 1.3 2009/08/03 21:55:53 ccovian Exp $
 * Autor: Gustavo Gonzalez.
 * Fecha: 03/12/2007
 *
 * Tipos de pizarron para los canales de operacion.
 */

DROP TABLE SICA_ADMIN.SC_TIPO_PIZARRON;

CREATE TABLE SICA_ADMIN.SC_TIPO_PIZARRON (
        ID_TIPO_PIZARRON NUMBER NOT NULL PRIMARY KEY,
        GENERA_PIZARRON CHAR(1) NOT NULL, 
        DESCRIPCION VARCHAR2(100) NOT NULL
);

CREATE PUBLIC SYNONYM SC_TIPO_PIZARRON FOR SICA_ADMIN.SC_TIPO_PIZARRON;
INSERT INTO SC_TIPO_PIZARRON (GENERA_PIZARRON, DESCRIPCION) VALUES ('N', 'PROMOCION MAYOREO')
/