/*
 * $Id: SC_TIPO_LINEA_CREDITO.sql,v 1.11 2008/02/22 18:25:13 ccovian Exp $
 * Autor: Javier Cordova (jcordova)
 * Fecha: 12/08/2005
 */

DROP TABLE SICA_ADMIN.SC_TIPO_LINEA_CREDITO;

CREATE TABLE SICA_ADMIN.SC_TIPO_LINEA_CREDITO (
  USA_LINEA_CREDITO NUMBER NOT NULL PRIMARY KEY
, DESCRIPCION VARCHAR2(20) NOT NULL
);

CREATE PUBLIC SYNONYM SC_TIPO_LINEA_CREDITO FOR SICA_ADMIN.SC_TIPO_LINEA_CREDITO;
/