-- Inserta el registro inicial para la tabla SC_SISTEMA

INSERT INTO SICA_ADMIN.SC_SISTEMA (ID_SISTEMA,DESCRIPCION,USUARIO_CREACION,FECHA_CREACION,USUARIO_ULT_MODIF,FECHA_ULT_MODIF) 
	VALUES (1, 'Sistema de Cambios', 0, SYSDATE, 0, SYSDATE);
