/*
 * $Id: BUP_CANAL.sql,v 1.11 2008/02/22 18:25:43 ccovian Exp $
 * Autor: Ricardo Legorreta H, Javier Cordova (jcordova).
 * Fecha: 11/02/2005
 *
 */

DROP TABLE BUPIXE.BUP_CANAL;

CREATE TABLE BUPIXE.BUP_CANAL (
        CLAVE_CANAL VARCHAR2(8) NOT NULL PRIMARY KEY,
        NOMBRE_CANAL VARCHAR2(10) NOT NULL,
        DESCRIPCION_CANAL VARCHAR2(20) NOT NULL
);

CREATE PUBLIC SYNONYM BUP_CANAL FOR BUPIXE.BUP_CANAL;
/