/*
 * $Id: BUP_TIPO_IVA.sql,v 1.10 2008/02/22 18:25:43 ccovian Exp $
 * Autor: Edgar Leija
 * Fecha: 03/05/2007
 *
 */

DROP TABLE SICA_ADMIN.BUP_TIPO_IVA;

CREATE TABLE SICA_ADMIN.BUP_TIPO_IVA (
        CLAVE_TIPO_IVA CHAR(3) NOT NULL PRIMARY KEY,
        DESCRIPCION VARCHAR2(30) NOT NULL,
        PORC_IVA NUMBER(4,2) NOT NULL
);

CREATE PUBLIC SYNONYM BUP_TIPO_IVA FOR SICA_ADMIN.BUP_TIPO_IVA;
/
