/*
 * $Id: BUP_PERSONA_CLAVE_REFERENCIA.sql,v 1.3 2008/02/22 18:25:43 ccovian Exp $
 * Autor: Javier Cordova.
 * Fecha: 11/10/2007
 *
 * Para Pagos Referenciados.
 */

DROP TABLE BUPLEGO.BUP_PERSONA_CLAVE_REFERENCIA;

CREATE TABLE BUPLEGO.BUP_PERSONA_CLAVE_REFERENCIA (
    ID_PERSONA_ANTERIOR NUMBER NOT NULL PRIMARY KEY,
    ID_PERSONA NUMBER NOT NULL,
    CLAVE_REFERENCIA VARCHAR2(10) NOT NULL,
    STATUS VARCHAR2(15) NULL,
    USUARIO_ULT_MOD VARCHAR2(33) NULL,
    FECHA_ULT_MOD DATE NOT NULL
);

CREATE PUBLIC SYNONYM BUP_PERSONA_CLAVE_REFERENCIA FOR BUPLEGO.BUP_PERSONA_CLAVE_REFERENCIA;
/