/*
 * $Id: BUP_CONTRATO_SICA.sql,v 1.11 2008/02/22 18:25:43 ccovian Exp $
 * Autor: Ricardo Legorreta H.
 * Fecha: 17/02/2005
 *
 * Subclase de BUP_CUENTA_CONTRATO donde se almacenan las cuentas del SICA.
 */

DROP TABLE BUPIXE.BUP_CONTRATO_SICA;

CREATE TABLE BUPIXE.BUP_CONTRATO_SICA (
        NO_CUENTA VARCHAR2(33) NOT NULL PRIMARY KEY,
        ID_GRUPO_EMPRESARIAL NUMBER NULL,
        MONTO_OPERACIONES_MES NUMBER(16,2) NOT NULL,
        NUMERO_EXCEPCIONES_DOC NUMBER(3) NULL,
        NUMERO_OPERACIONES_MES NUMBER(3) NOT NULL,
        RECURRENTE CHAR(1) NOT NULL,
        SALDO_DEUDOR NUMBER(10,2) NOT NULL,
        PORCENTAJE_COMISION NUMBER(10,6) NULL
);

CREATE PUBLIC SYNONYM BUP_CONTRATO_SICA FOR BUPIXE.BUP_CONTRATO_SICA;
/
