CREATE OR REPLACE VIEW BUPIXE.SEGU_USUARIO_VERSION  (
    ID_USUARIO,
    CLAVE_USUARIO,
    TIPO_USUARIO,
    PASSPHRASE,
    PASSWORD,
    NUMERO_SERIE,
    ID_PERSONA,
    ADMINISTRA_IXE,
    EMAIL,
    STATUS,
    FECHA_ALTA,
    REINICIALIZA_PASSWORD,
    FECHA_ULT_MOD,
    ID_USUARIO_ULT_MOD,
    ID_USUARIO_ALTA,
    VERSION
) 
AS
 SELECT
    U.ID_USUARIO,U.CLAVE_USUARIO,U.TIPO_USUARIO,U.PASSPHRASE,U.PASSWORD,U.NUMERO_SERIE,
    U.ID_PERSONA,U.ADMINISTRA_IXE,U.EMAIL,U.STATUS,U.FECHA_ALTA,U.REINICIALIZA_PASSWORD,
    U.FECHA_ULT_MOD,U.ID_USUARIO_ULT_MOD,U.ID_USUARIO_ALTA, 
    (SELECT MAX
        (UH.VERSION)
    FROM 
        SEGU_USUARIO_HISTORIA UH
    WHERE
        UH.ID_USUARIO = U.ID_USUARIO) AS VERSION
FROM SEGU_USUARIO U;
/
