/*
 * $Id: SICA_VARIACION.sql,v 1.11 2008/02/22 18:25:43 ccovian Exp $
 * Autor: Javier Cordova.
 * Fecha: 17/10/2005
 *
 */

DROP TABLE SICA_ADMIN.SICA_VARIACION;

CREATE TABLE SICA_ADMIN.SICA_VARIACION
(
        ID_VARIACION NUMBER NOT NULL,
        FECHA DATE NOT NULL,
        VARIACION_MID FLOAT(126) NOT NULL,
        VARIACION_VTA_SPOT FLOAT(126) NOT NULL,
        VARIACION_VTA_SPOT_ASK FLOAT(126) NOT NULL,
        MXN_EUR_VARIACION_VTA_SPOT FLOAT(126) NULL,
        MXN_EUR_VARIACION_VTA_SPOT_ASK FLOAT(126) NULL,
        CAD_VARIACION_VTA_SPOT FLOAT(126) NULL,
        CAD_VARIACION_VTA_SPOT_ASK FLOAT(126) NULL,
        CHF_VARIACION_VTA_SPOT FLOAT(126) NULL,
        CHF_VARIACION_VTA_SPOT_ASK FLOAT(126) NULL,
        EUR_VARIACION_VTA_SPOT FLOAT(126) NULL,
        EUR_VARIACION_VTA_SPOT_ASK FLOAT(126) NULL,
        GBP_VARIACION_VTA_SPOT FLOAT(126) NULL,
        GBP_VARIACION_VTA_SPOT_ASK FLOAT(126) NULL,
        JPY_VARIACION_VTA_SPOT FLOAT(126) NULL,
        JPY_VARIACION_VTA_SPOT_ASK FLOAT(126) NULL,
        CONSTRAINT PK_SICA_VARIACION PRIMARY KEY (ID_VARIACION)
);

COMMENT ON COLUMN SICA_VARIACION.ID_VARIACION
IS
    'Identificador del registro';
    COMMENT ON COLUMN SICA_VARIACION.FECHA
IS
    'Fecha y hora de la variación';
    COMMENT ON COLUMN SICA_VARIACION.VARIACION_MID
IS
    'Variación de la variable MID';

CREATE PUBLIC SYNONYM SICA_VARIACION FOR BUPIXE.SICA_VARIACION;

DROP SEQUENCE BUPIXE.SICA_VARIACION_SEQ;

CREATE SEQUENCE BUPIXE.SICA_VARIACION_SEQ;

CREATE PUBLIC SYNONYM SICA_VARIACION_SEQ FOR BUPIXE.SICA_VARIACION_SEQ;
/
