/*
 * $Id: SC_DIVISA.sql,v 1.13 2008/02/22 18:25:29 ccovian Exp $
 * Autor: Javier Cordova (jcordova)
 * Fecha: 12/10/2005
 */

insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('USD', 'Dólar Americano', '/sica/images/banderas/USD.jpg', '10', 'F', 1, 'N', 'US DOLLAR', null, 2, null);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('CAD', 'Dólar Canadiense', '/sica/images/banderas/CAD.jpg', '14', 'F', 2, 'S', 'CANADIAN DOLLAR', null, 95, null);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('EUR', 'Euro', '/sica/images/banderas/EUR.jpg', '22', 'F', 3, 'N', 'EURO', null, 78, null);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('GBP', 'Libra Esterlina', '/sica/images/banderas/GBP.jpg', '16', 'F', 4, 'N', 'POUND STERLING', null, 23, null);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('CHF', 'Franco Suizo', '/sica/images/banderas/CHF.jpg', '18', 'F', 5, 'S', 'SWISS FRANC', null, 88, null);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('MXN', 'Pesos Mexicanos', '/sica/images/banderas/MXN.jpg', '1 ', 'N', 7, 'N', 'MEXICAN PESO', null, 1, null);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('CRC', 'Colon, Costa Rica', null, '33', 'N', 100, 'N', 'COSTA RICAN COLON', null, 91, null);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('NZD', 'Dólares, Nueva Zelan', null, '31', 'N', 100, 'N', 'NEW ZEALAND DOLLAR', null, 38, null);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('AUD', 'Dólares, Australia', null, '23', 'N', 100, 'N', 'AUSTRALIAN DOLLAR', null, 106, null);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('TWD', 'Dólar Nvo, Taiwan', null, '34', 'N', 100, 'N', 'NEW TAIWAN DOLLAR', null, 17, null);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('XOT', 'Onza Troy, 200 Plata', null, '36', 'M', 100, 'N', null, 'OZP', 46, 1);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('DKK', 'Corona Danesa', null, '27', 'N', 100, 'N', null, null, 86, null);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('XPL', 'Plata Libertad, 250', null, '37', 'M', 100, 'N', null, 'OZP', 128, 1);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('XCE', 'Centenarios, 50 Oro', null, '50', 'M', 100, 'N', null, 'ORO', 113, 50);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('XAZ', 'Aztecas, 20 Oro N', null, '51', 'M', 100, 'N', null, 'ORO', 112, 20);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('XHI', 'Hidalgos, 10 Oro', null, '52', 'M', 100, 'N', null, 'ORO', 126, 10);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('XMH', 'Medio Hidalgo, 5 Oro', null, '53', 'M', 100, 'N', null, 'ORO', 127, 5);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('XCH', 'Cuarto Hidalgo 2.5 O', null, '54', 'M', 100, 'N', null, 'ORO', 114, 2.5);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('XQH', 'Quinto Hidalgo 2 Oro', null, '55', 'M', 100, 'N', null, 'ORO', 129, 2);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('NOK', 'Coronas Noruegas', null, '24', 'N', 100, 'N', 'NORWEGIAN KRONE', null, 39, null);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('JPY', 'Yen', '/sica/images/banderas/JPY.jpg', '19', 'F', 6, 'S', 'JAPANESE YEN', null, 56, null);
insert into SICA_ADMIN.SC_DIVISA (ID_DIVISA, DESCRIPCION, ICONO_FNAME, ID_MONEDA, TIPO, ORDEN, DIVIDE, DESCRIPCION_EN, GRUPO, ID_MONEDA_MINDS, EQUIVALENCIA_METAL) values ('SEK', 'Corona Sueca', null, '32', 'N', 100, 'N', 'SWEDISH KRONA', null, 27, null);

COMMIT;
/