/*
 * $Id: SC_MAXIMO_DEAL.sql,v 1.12 2008/02/22 18:25:29 ccovian Exp $
 * Autor: Javier Cordova (jcordova)
 * Fecha: 12/10/2005
 */

insert into SICA_ADMIN.SC_MAXIMO_DEAL (ID_DIVISA, ID_MESA_CAMBIO, MONTO_MAXIMO) values ('USD', 1, 1000000);
insert into SICA_ADMIN.SC_MAXIMO_DEAL (ID_DIVISA, ID_MESA_CAMBIO, MONTO_MAXIMO) values ('CAD', 1, 55000);
insert into SICA_ADMIN.SC_MAXIMO_DEAL (ID_DIVISA, ID_MESA_CAMBIO, MONTO_MAXIMO) values ('GBP', 1, 1000000);
insert into SICA_ADMIN.SC_MAXIMO_DEAL (ID_DIVISA, ID_MESA_CAMBIO, MONTO_MAXIMO) values ('CHF', 1, 1000000);
insert into SICA_ADMIN.SC_MAXIMO_DEAL (ID_DIVISA, ID_MESA_CAMBIO, MONTO_MAXIMO) values ('YEN', 1, 50000000);
insert into SICA_ADMIN.SC_MAXIMO_DEAL (ID_DIVISA, ID_MESA_CAMBIO, MONTO_MAXIMO) values ('EUR', 1, 1000000);
insert into SICA_ADMIN.SC_MAXIMO_DEAL (ID_DIVISA, ID_MESA_CAMBIO, MONTO_MAXIMO) values ('JPY', 1, 1000000);

COMMIT;
/