/*
 * $Id: SC_MESA_CAMBIO.sql,v 1.12 2008/02/22 18:25:29 ccovian Exp $
 * Autor: Jean C. Favila.
 * Fecha: 06/01/2005
 *
 */

insert into SICA_ADMIN.SC_MESA_CAMBIO (ID_MESA_CAMBIO, NOMBRE, ID_DIVISA_REFERENCIA, REPORTA_BANXICO) values (1, 'OPERACION ', 'MXN', 'S');
insert into SICA_ADMIN.SC_MESA_CAMBIO (ID_MESA_CAMBIO, NOMBRE, ID_DIVISA_REFERENCIA, REPORTA_BANXICO) values (22, 'TRADER USD', 'USD', 'S');
insert into SICA_ADMIN.SC_MESA_CAMBIO (ID_MESA_CAMBIO, NOMBRE, ID_DIVISA_REFERENCIA, REPORTA_BANXICO) values (25, 'TRADER MXN', 'MXN', 'N');
insert into SICA_ADMIN.SC_MESA_CAMBIO (ID_MESA_CAMBIO, NOMBRE, ID_DIVISA_REFERENCIA, REPORTA_BANXICO) values (33, 'ESTRATEGIA', 'MXN', 'N');

COMMIT;
/