/*
 * $Id: SC_SPREAD_ACTUAL.sql,v 1.12 2008/02/22 18:25:29 ccovian Exp $
 * Autor: Javier Cordova (jcordova)
 * Fecha: 12/10/2005
 */

insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'EFECTI', 'USD', 56, '2007-07-09 07:39:51.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'CHVIAJ', 'USD', 57, '2007-07-09 07:40:02.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'DOCEXT', 'USD', 58, '2007-07-09 07:40:13.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'MEXDOL', 'USD', 59, '2007-07-09 07:40:29.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'CHVIAJ', 'EUR', 65, '2007-07-09 07:43:29.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'DOCEXT', 'EUR', 66, '2007-07-09 07:43:51.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'CHVIAJ', 'GBP', 69, '2007-07-09 07:44:42.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'DOCEXT', 'CHF', 74, '2007-07-09 07:46:17.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'EFECTI', 'CHF', 75, '2007-07-09 07:46:31.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'TRAEXT', 'CHF', 76, '2007-07-09 07:47:30.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (25, 'TPS', 'TRAEXT', 'CAD', 84, '2007-07-09 07:53:28.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'DOCEXT', 'JPY', 78, '2007-07-09 07:48:04.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (25, 'TPS', 'TRAEXT', 'USD', 83, '2007-07-09 07:52:55.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (22, 'TDL', 'TRAEXT', 'CAD', 90, '2007-07-09 07:56:09.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (22, 'TDL', 'TRAEXT', 'EUR', 91, '2007-07-09 07:57:03.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (22, 'TDL', 'TRAEXT', 'GBP', 92, '2007-07-09 07:58:02.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (22, 'TDL', 'TRAEXT', 'CHF', 93, '2007-07-09 07:58:27.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'CHVIAJ', 'CAD', 105, '2007-07-09 14:54:40.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'CHVIAJ', 'JPY', 119, '2007-09-05 10:58:54.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (33, 'EST', 'TRAEXT', 'USD', 123, '2007-10-10 12:59:38.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'TRAEXT', 'USD', 48, '2007-07-06 10:51:32.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'CHVIAJ', 'USD', 55, '2007-07-06 10:57:09.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'DOCEXT', 'USD', 53, '2007-07-06 10:57:09.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'EFECTI', 'USD', 52, '2007-07-06 10:54:04.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'MEXDOL', 'USD', 54, '2007-07-06 10:57:09.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'EFECTI', 'CAD', 106, '2007-07-09 14:54:40.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'DOCEXT', 'CAD', 104, '2007-07-09 14:54:39.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'TRAEXT', 'CAD', 8, '2007-06-24 11:29:18.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'CHVIAJ', 'EUR', 102, '2007-07-09 14:49:04.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'DOCEXT', 'EUR', 101, '2007-07-09 14:49:04.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'EFECTI', 'EUR', 96, '2007-07-09 14:44:49.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'TRAEXT', 'EUR', 12, '2007-06-24 11:30:28.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'DOCEXT', 'GBP', 108, '2007-07-09 14:56:07.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'EFECTI', 'GBP', 110, '2007-07-09 14:56:07.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'TRAEXT', 'GBP', 15, '2007-06-24 11:31:38.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'DOCEXT', 'CHF', 111, '2007-07-09 14:57:34.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'EFECTI', 'CHF', 112, '2007-07-09 14:57:34.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'TRAEXT', 'CHF', 18, '2007-06-24 11:32:20.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'DOCEXT', 'JPY', 113, '2007-07-09 14:59:33.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'EFECTI', 'JPY', 114, '2007-07-09 14:59:33.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'TRAEXT', 'JPY', 21, '2007-06-24 11:32:47.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'TRAEXT', 'USD', 60, '2007-07-09 07:41:01.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'CHVIAJ', 'CAD', 61, '2007-07-09 07:41:49.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'DOCEXT', 'CAD', 62, '2007-07-09 07:42:13.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'EFECTI', 'CAD', 63, '2007-07-09 07:42:28.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'TRAEXT', 'CAD', 64, '2007-07-09 07:42:45.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'EFECTI', 'EUR', 67, '2007-07-09 07:44:11.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'TRAEXT', 'EUR', 68, '2007-07-09 07:44:19.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'DOCEXT', 'GBP', 70, '2007-07-09 07:45:03.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'EFECTI', 'GBP', 71, '2007-07-09 07:45:22.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'TRAEXT', 'GBP', 72, '2007-07-09 07:45:45.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'CHVIAJ', 'CHF', 73, '2007-07-09 07:46:03.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'EFECTI', 'JPY', 79, '2007-07-09 07:49:00.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'MOP', 'TRAEXT', 'JPY', 80, '2007-07-09 07:49:11.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (25, 'TPS', 'TRAEXT', 'CHF', 87, '2007-07-09 07:54:16.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (25, 'TPS', 'TRAEXT', 'EUR', 85, '2007-07-09 07:53:43.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (25, 'TPS', 'TRAEXT', 'GBP', 86, '2007-07-09 07:53:59.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (25, 'TPS', 'TRAEXT', 'JPY', 88, '2007-07-09 07:54:52.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (22, 'TDL', 'TRAEXT', 'JPY', 94, '2007-07-09 07:58:45.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'CHVIAJ', 'GBP', 109, '2007-07-09 14:56:07.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (33, 'EST', 'CHVIAJ', 'USD', 122, '2007-10-10 12:59:25.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'CHVIAJ', 'JPY', 118, '2007-09-05 10:13:49.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'TRANAL', 'EUR', 121, '2007-10-03 13:15:42.0');
insert into SICA_ADMIN.SC_SPREAD_ACTUAL (ID_MESA_CAMBIO, ID_CANAL, CLAVE_FORMA_LIQUIDACION, ID_DIVISA, ID_SPREAD, ULTIMA_MODIFICACION) values (1, 'PMY', 'CHVIAJ', 'CHF', 116, '2007-08-22 09:37:22.0');

COMMIT;
/