-- Revoke Permisos para SICA_BATCH
REVOKE ALL ON SICA_ADMIN.SICA_VARIACION FROM SICA_BATCH
REVOKE ALL ON SICA_ADMIN.SICA_VARIACION_SEQ FROM SICA_BATCH
REVOKE ALL ON SICA_ADMIN.SC_PARAMETRO FROM SICA_BATCH
REVOKE ALL ON SICA_ADMIN.SC_PRECIO_REFERENCIA FROM SICA_BATCH
REVOKE ALL ON SICA_ADMIN.SC_FACTOR_DIVISA FROM SICA_BATCH
REVOKE ALL ON SICA_ADMIN.SC_H_PRECIO_REFERENCIA FROM SICA_BATCH
REVOKE ALL ON SICA_ADMIN.SC_H_FACTOR_DIVISA FROM SICA_BATCH