--Permisos para SICA_BATCH
GRANT SELECT,UPDATE,DELETE,INSERT ON SICA_ADMIN.SICA_VARIACION TO SICA_BATCH
GRANT SELECT ON SICA_ADMIN.SICA_VARIACION_SEQ TO SICA_BATCH
GRANT SELECT ON SICA_ADMIN.SC_PARAMETRO TO SICA_BATCH
GRANT SELECT,DELETE,INSERT ON SICA_ADMIN.SC_PRECIO_REFERENCIA TO SICA_BATCH
GRANT SELECT,DELETE,INSERT ON SICA_ADMIN.SC_FACTOR_DIVISA TO SICA_BATCH
GRANT SELECT,DELETE,INSERT ON SICA_ADMIN.SC_H_PRECIO_REFERENCIA TO SICA_BATCH
GRANT SELECT,DELETE,INSERT ON SICA_ADMIN.SC_H_FACTOR_DIVISA TO SICA_BATCH