<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id: CapturaDealApplet.script,v 1.8 2008/02/22 18:25:18 ccovian Exp $ -->
<!DOCTYPE script PUBLIC
	"-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
	"http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">

<script>
    <body><![CDATA[
        try {
			window.top.frames[2].document.getElementById('pizarraApplet').setCapturaDeal(true);
		}
		catch (ex) {
		}
    ]]></body>
</script>