<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id: CerrarVentanaConsCtas.script,v 1.7 2008/02/22 18:25:18 ccovian Exp $ -->
<!DOCTYPE script PUBLIC
	"-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
	"http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">

<script>
    <body><![CDATA[
		window.close();
		parent.opener.parent.frames[1].location = '?service=page/AsignacionCtas';
    ]]></body>
</script>
