<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id: FirstField.script,v 1.7 2008/02/22 18:25:18 ccovian Exp $ -->
<!DOCTYPE script PUBLIC
	"-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
	"http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">

<script>
    <input-symbol key="textField" class="java.lang.String" required="yes" />
    <initialization>
        <![CDATA[
                ${textField}.focus();
                ${textField}.select();
 ]]></initialization>
</script>