delete from sc_parametro
where id_parametro in ('OMM_CONNECTION_PROPERTIES_FILE_NAME',
'OMM_DACS_USERNAME',
'OMM_SESSION_NAME',
'OMM_LOGIN_TIMEOUT',
'OMM_MARKETFEED_TIMEOUT',
'OMM_SERVICE_NAME',
'OMM_RIC_LIST',
'OMM_INTERESTVIEW_LIST',
'OMM_MARKETFEED_ENDTIME');

SELECT * from sc_parametro
where id_parametro in ('OMM_CONNECTION_PROPERTIES_FILE_NAME',
'OMM_DACS_USERNAME',
'OMM_SESSION_NAME',
'OMM_LOGIN_TIMEOUT',
'OMM_MARKETFEED_TIMEOUT',
'OMM_SERVICE_NAME',
'OMM_RIC_LIST',
'OMM_INTERESTVIEW_LIST',
'OMM_MARKETFEED_ENDTIME');
