--
-- DROP a Tablas de Control Respaldo
--

set serveroutput on size 1000000

DROP PUBLIC SYNONYM SC_RESPALDO_TABLA_LOG;
DROP TABLE SICA_ADMIN.SC_RESPALDO_TABLA_LOG;

DROP PUBLIC SYNONYM SC_RESPALDO_TABLA;
DROP TABLE SICA_ADMIN.SC_RESPALDO_TABLA;

DROP PUBLIC SYNONYM SC_RESPALDO;
DROP TABLE SICA_ADMIN.SC_RESPALDO;

DROP PUBLIC SYNONYM SC_CAT_TABLA_RESPALDO;
DROP TABLE SICA_ADMIN.SC_CAT_TABLA_RESPALDO;

